services:
  - type: web
    name: unkown-service
    env: node
    envVars:
      - key: NODE_VERSION
        value: 18.9.0
    repo: https://gitlab.com/somebozo/dont-worry-about-it # optional
    plan: free
    buildCommand: npm install
    startCommand: node .
    rootDir: ./

